[DOPS-2860]: create subquery endpoint
sora-xor/sora-subquery-dictionary pull request #4
Opened 2023-11-15 14:15 UTC by f33r0

# Task

[DOPS-2860]: create subquery endpoint

## Changes

1.  Created CI

## Author

Signed-off-by: Nikita Zaporozhets <zaporozhets@soramitsu.co.jp>

[DOPS-2860]: https://soramitsu.atlassian.net/browse/DOPS-2860

2023-11-15 14:21 UTC, Cre-eD approved these changes

2023-11-16 06:39 UTC, wpi86 requested changes

2023-11-16 06:39 UTC, wpi86 commented on Jenkinsfile
> +    test:               false,
Why?

2023-11-16 06:39 UTC, wpi86 commented on Jenkinsfile
> +    dockerImageTags:    ['feauture/dops-2860': 'dictionary']
Forgot?

2023-12-11 11:35 UTC, merged